# --- 基礎服務設定 ---
listener 1883
allow_anonymous true
persistence false

# 日誌：正式環境僅 error/warning；除錯可加 log_type notice / information
log_dest stdout
log_type error
log_type warning
# log_type notice
# log_type information

# ========== 橋接 meshbridge-broker (明文 1883) ==========
connection ${MESHGATE_BRIDGE_CONNECTION_NAME}_meshbridge-broker
address meshbridge-broker:1883

# 身分驗證
remote_username meshdev
remote_password large4cats
local_clientid ${MESHGATE_BRIDGE_CONNECTION_NAME}_meshbridge-broker

bridge_protocol_version mqttv311

# Bridge topic 規則
topic 2/e/+/+ in 0 msh/TW/meshbridge/ msh/TW/
topic 2/json/+/+ in 0 msh/TW/meshbridge/ msh/TW/
topic 2/map/+ in 0 msh/TW/meshbridge/ msh/TW/
topic 2/+/e/+/+ in 0 msh/TW/meshbridge/ msh/TW/
topic 2/+/json/+/+ in 0 msh/TW/meshbridge/ msh/TW/
topic 2/+/map/+ in 0 msh/TW/meshbridge/ msh/TW/
topic 2/+/+/e/+/+ in 0 msh/TW/meshbridge/ msh/TW/
topic 2/+/+/json/+/+ in 0 msh/TW/meshbridge/ msh/TW/
topic 2/+/+/map/+ in 0 msh/TW/meshbridge/ msh/TW/
topic msh/TW/2/e/# out 0
topic msh/TW/2/map/+ out 0

cleansession true
start_type automatic
keepalive_interval 60

# ========== 橋接 Liam Cottle's Map (純上傳, 明文 1883) ==========
connection ${MESHGATE_BRIDGE_CONNECTION_NAME}_mqtt.meshtastic.liamcottle.net
address mqtt.meshtastic.liamcottle.net:1883

# 身分驗證
remote_username uplink
remote_password uplink
local_clientid ${MESHGATE_BRIDGE_CONNECTION_NAME}_mqtt.meshtastic.liamcottle.net

bridge_protocol_version mqttv311

# Bridge topic 規則
topic msh/TW/2/map/+ out 0

cleansession true
start_type automatic
keepalive_interval 60
